name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          pip install -r requirements.txt    

      - name: Black
        run: black --diff --check src/
      - name: Isort
        run: isort --check-only --diff src/
#      - name: Mypy
#        run: mypy src/
#      - name: Flake8
#        run: flake8 src/
      - name: Test module
        run: pytest tests/my-directory
   
