name: CI
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          python -m venv venv                # Создание виртуального окружения
          source venv/bin/activate           # Активация виртуального окружения
          pip install -r requirements.txt    # Установка зависимостей
          pip install black                   # Установка black

      - name: Run test
        run: |
          source venv/bin/activate
      - name: Black
        run: black --diff --check src/*.py
      - name: Isort
        run: isort --check only --diff src/*.py
      - name: Mypy
        run: mypy src/*.py
   
